################################################################################
# Copyright (c) 2021 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 22-03-2021                                                             #
# Author(s): Gabriele Graffieti                                                #
# E-mail: contact@continualai.org                                              #
# Website: avalanche.continualai.org                                           #
################################################################################

name: test coverage coverall

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/test-coverage-coveralls.yml'
      - 'environment.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/test-coverage-coveralls.yml'
      - 'environment.yml'

jobs:
  unit-test:
    if: github.repository == 'ContinualAI/avalanche-rl'
    name: unit test
    runs-on: ubuntu-latest
    container:
      image: nicklucche/avalanche-rl:latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: download atari roms
      #   run: |
      #     wget http://www.atarimania.com/roms/Roms.rar
      #     unar Roms.rar
      #     python -m atari_py.import_roms Rars/
      - name: install coverage.py and coverralls
        run: |
          pip install coverage
          pip install coveralls
          pip install pytest
          pip install pytest-cov
      - name: python unit test
        id: unittest
        run: |
          coverage run -m pytest
      - name: Upload coverage data to coveralls.io
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    if: github.repository == 'ContinualAI/avalanche-rl'
    name: Indicate completion to coveralls.io
    needs: unit-test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
